# Обработка ошибок
1. Текст ошибки указывается в последней строчке
2. Все что перед ней - место, где ошибка произошла
3. Есть встроенные типы ошибок, но можно создавать и свои

In [1]:
1/0

ZeroDivisionError: division by zero

Некоторые типы ошибок из документации (точнее [перевода](https://pythonworld.ru/tipy-dannyx-v-python/isklyucheniya-v-python-konstrukciya-try-except-dlya-obrabotki-isklyuchenij.html)):
- ZeroDivisionError - деление на ноль
- ImportError - не удалось импортирование модуля или его атрибута (надо установить эту библиотеку)
- IndexError - индекс не входит в диапазон элементов.
- KeyError - несуществующий ключ (в словаре, множестве или другом объекте)
- MemoryError - недостаточно памяти
- SyntaxError - синтаксическая ошибка (вы опечатались или не закрыли скобку)
- TypeError - операция применена к объекту несоответствующего типа
- ValueError - функция получает аргумент правильного типа, но некорректного значения
- Warning - предупреждение (текст на красном фоне в юпитере это предупреждение, а не ошибка)

In [2]:
# эту строку можно перевести в число
some_num = '123'

In [3]:
float(some_num)

123.0

In [4]:
# а эту уже нет (по крайней мере в десятичном счислении)
ups = '123a'

In [5]:
# ValueError - тип ошибки, далее пояснение что произошло
# ----> 1 float(ups) - в каком месте кода произошла ошибка
float(ups)

ValueError: could not convert string to float: '123a'

Пример ошибки внутри функции

In [6]:
def square_sum(*args):
    total_sum = 0
    for arg in args:
        total_sum += arg**2
    
    return total_sum

In [7]:
square_sum(1, 2, 3)

14

In [8]:
# пытаемся применить к операцию возведения в квадрат к строке
# ----> 1 square_sum(1, 2, '3') - в какой функции произошла ошибка
# ----> 4         total_sum += arg**2 - в какой именно строке произошла ошибка

square_sum(1, 2, '3')

TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

## Как сделать, чтобы цикл с расчетом не падал каждый раз

In [9]:
float('123a')

ValueError: could not convert string to float: '123a'

In [10]:
try:
    # ваш код, где может произойти ошибка
    float('123a')

except:
    # код, который выполняется в случае ошибки
    print('Ошибка')
    
print('Результат')

Ошибка
Результат

In [12]:
data = ['90', '60', '90', '240tot', ]

for num in data:
    print(int(num))

90
60
90

ValueError: invalid literal for int() with base 10: '240tot'

In [14]:
data = ['90', '60', '90', '240tot', ]
total_sum = 0
wrong_lines = 0

for num in data:
    try:
        total_sum += float(num)

    except:
        wrong_lines += 1
        print('Ошибка в данных: {}'.format(num))
    
print('Итого', total_sum)

Ошибка в данных: 240tot
Итого 240.0

In [15]:
wrong_lines

1

In [ ]:
pi = 3.141516
print(f'Ошибка в данных: {}, результат {pi}')

In [ ]:
print('Ошибка в данных: {}'.format(num))

Как сохранить всю информацию об ошибке?

In [16]:
# полная версия traceback
import traceback

try:
    float('123fff')

except Exception:
    print(traceback.print_exc())
    
print('Проехали')

None
Проехали

Traceback (most recent call last):
  File "<ipython-input-16-aec2760d579a>", line 5, in <module>
    float('123fff')
ValueError: could not convert string to float: '123fff'

### Упражнение
Создайте словарь stats = {'monday': 100, 'tuesday': 200}. 

Какой тип ошибки вызовет обращение stats['wednesday']

In [17]:
stats = {'monday': 100, 'tuesday': 200}

In [18]:
stats['wednesday']

KeyError: 'wednesday'

### Блок finally

In [23]:
try:
    print(stats["wednesday"])
    
except IndexError:
    print("Ошибка индекса")
    
except KeyError:
    print("Ошибка ключа")
    1/0
    
finally:
    print('Эта строчка будет выполнена всегда')

Ошибка ключа
Эта строчка будет выполнена всегда

ZeroDivisionError: division by zero

In [ ]:
try:
    f = open()
    ....
except:

finally:
    f.close()

In [ ]:
with open():
    try:
    except:

### Более жизненный пример

In [24]:
with open('real_data.txt', 'r') as f:
    for line in f:
        print(line.strip())

05.10.16 23:18	1010	20,2
09.10.2016T 21:40:00	1036	15,6
05.10.16 3:23	1041
05.10.16 23:19	1041
01.10.16 4:57	1042	14,8
01.10.16 23:29	1042	14,4
03.10.16 20:20	1042	14
04.10.16 0:35	1042	20
04.10.16 13:46	1042	16,2
04.10.16 17:34	1042	11
05.10.16 15:15	1042	10800000
06.10.16 20:45	1042	22,6
07.10.16 2:54	1042	22,4
07.10.16 5:02	1042	24,4
07.10.16 6:35	1042	16,6
08.10.2016T 16:46:00	1042	8,6
01.10.16 13:39	1047
05.10.16 21:41	1047
07.10.16 9:59	1052	24
08.10.2016T 19:36:00	1052	18,8
04.10.16 11:12	1057
09.10.2016T 2:47:00	1057
09.10.2016T 16:27:00	1062	11,2
05.10.16 4:38	1067	19
04.10.16 9:56	1078	23,4
04.10.16 14:36	1085	17
05.10.16 16:41	1096	20,8
01.10.16 11:55	1098	15,6
01.10.16 14:16	1100
02.10.16 1:39	1100
02.10.16 2:49	1100
02.10.16 13:05	1100
03.10.16 4:04	1100
03.10.16 6:58	1100
03.10.16 15:01	1100
04.10.16 23:43	1100
05.10.16 5:46	1100
06.10.16 0:31	1100
06.10.16 9:25	1100
08.10.2016T 15:15:00	1100
07.10.16 9:06	1105	16,2
01.10.16 4:30	1108	17,8
01.10.16 18:16	1108	18,8
02.10.16 2:58	1108	20000000
02.10.16 6:01	1108	21
02.10.16 20:03	1108	16,6
04.10.16 2:56	1108	20
04.10.16 6:57	1108	19,8
06.10.16 6:46	1108	16,8
09.10.2016T 8:33:00	1108	24000000
08.10.2016T 8:02:00	1111	12
05.10.16 5:25	1112	10,2
09.10.2016T 0:03:00	1112	24
06.10.16 10:09	1113	15,8
09.10.2016T 12:09:00	1113	22
05.10.16 18:00	1114	17,4
06.10.16 17:58	1114	14,8
05.10.16 23:19	1116	20
01.10.16 23:13	1118	11,6
09.10.2016T 21:14:00	1118	20
05.10.16 16:30	1123	16
06.10.16 5:27	1123	11,2
01.10.16 17:46	1128	12,2
04.10.16 5:00	1134
06.10.16 12:01	1134
01.10.16 15:58	1135
02.10.16 3:19	1135
02.10.16 19:24	1135
04.10.16 10:40	1135
06.10.16 6:06	1135
06.10.16 16:08	1135
08.10.2016T 0:31:00	1135
08.10.2016T 10:16:00	1135
08.10.2016T 23:10:00	1135
01.10.16 22:28	1136	21,6
03.10.16 23:03	1136	17,4
03.10.16 8:06	1140	22
04.10.16 10:01	1140	22
01.10.16 16:53	1141	16
05.10.16 3:31	1145	16
06.10.16 4:00	1145	20
02.10.16 8:08	1149	10
07.10.16 16:12	1149	21,2
08.10.2016T 6:55:00	1149	30,4
08.10.2016T 22:55:00	1149	18800000
09.10.2016T 4:10:00	1149	14
09.10.2016T 10:26:00	1149	22
09.10.2016T 22:22:00	1149	16
07.10.16 6:57	1150	12,6
02.10.16 12:03	1154	13,4
04.10.16 22:51	1154	13,6
04.10.16 9:28	1159	10,2
04.10.16 13:34	1159	17,4
08.10.2016T 9:43:00	1164	22,4
07.10.16 14:57	1167	11,4
07.10.16 20:25	1175	14
06.10.16 12:48	1181	22,4
07.10.16 9:54	1182	18
10.10.16 2:35	1182	17
04.10.16 13:49	1193	24800000
09.10.2016T 20:49:00	1193	16,6
01.10.16 5:12	1198	17,8
06.10.16 7:52	1198	9
06.10.16 5:15	1201	10,6
05.10.16 13:55	1203
06.10.16 5:56	1203
01.10.16 16:10	1207	16,6
02.10.16 1:24	1207	24,2
02.10.16 21:17	1207	20,4
03.10.16 16:08	1207	25,6
04.10.16 17:29	1207	19,8
05.10.16 1:39	1207	16,4
05.10.16 6:33	1207	16,2
05.10.16 18:57	1207	17
05.10.16 20:51	1207	16,8
07.10.16 8:55	1207	19,8
07.10.16 17:40	1207	15,6
08.10.2016T 23:36:00	1207	19,2
09.10.2016T 10:25:00	1207	23,2
09.10.2016T 21:04:00	1207	10,8
04.10.16 7:38	1208	24,4
09.10.2016T 14:53:00	1208	13,4
05.10.16 17:15	1209	12
03.10.16 6:16	1213	18,6
06.10.16 10:04	1213	16,6
01.10.16 16:52	1218	12200000
09.10.2016T 19:10:00	1218	22400000
02.10.16 8:42	1219	15,4
03.10.16 19:32	1223	17,2
06.10.16 22:11	1223	17600000
08.10.2016T 15:18:00	1224	16,4
01.10.16 4:41	1226
03.10.16 9:32	1226
07.10.16 18:32	1228	18,8
08.10.2016T 13:21:00	1228	17,6
03.10.16 15:47	1230	20,6
01.10.16 9:02	1233
01.10.16 10:27	1233
02.10.16 22:01	1236	17,4
05.10.16 5:27	1238	13,6
09.10.2016T 14:43:00	1238	17,6
04.10.16 22:25	1242	18,4
06.10.16 4:54	1243	20,4
06.10.16 14:28	1243	20
01.10.16 4:27	1246	17,8
02.10.16 4:27	1246
02.10.16 8:45	1246
02.10.16 16:58	1246
02.10.16 17:30	1246
02.10.16 19:46	1246
03.10.16 2:05	1246
03.10.16 2:57	1246
03.10.16 7:19	1246
03.10.16 12:15	1246
03.10.16 14:58	1246
03.10.16 19:43	1246
04.10.16 7:27	1246
04.10.16 9:08	1246
04.10.16 13:52	1246
04.10.16 16:34	1246
05.10.16 0:27	1246
05.10.16 6:36	1246
05.10.16 12:59	1246
05.10.16 16:52	1246
05.10.16 17:26	1246
06.10.16 6:48	1246
08.10.2016T 2:53:00	1246
10.10.16 0:59	1246
01.10.16 16:30	1248	13,2
01.10.16 21:06	1248	28,8
02.10.16 7:12	1252	22
04.10.16 13:51	1252	15,6
01.10.16 12:36	1253	13,6
04.10.16 17:11	1253	8,6
02.10.16 16:22	1258	22
08.10.2016T 19:34:00	1258	20
02.10.16 10:36	1263	12,6
03.10.16 6:10	1263	18
02.10.16 21:42	1267
04.10.16 9:02	1267
04.10.16 12:10	1267
04.10.16 15:40	1267
04.10.16 18:37	1267
04.10.16 21:29	1267
05.10.16 21:11	1267
05.10.16 22:09	1267
06.10.16 3:58	1267
06.10.16 11:16	1267
06.10.16 19:20	1267
07.10.16 10:18	1267
08.10.2016T 18:18:00	1267
09.10.2016T 4:41:00	1267
09.10.2016T 9:13:00	1267
09.10.2016T 15:37:00	1267
09.10.2016T 18:56:00	1267
05.10.16 2:48	1268	16,4
07.10.16 19:36	1268	16
02.10.16 14:12	1269	22
07.10.16 3:29	1270	21,8
01.10.16 8:56	1273	14,6
08.10.2016T 13:49:00	1273	22
07.10.16 6:00	1274	25
04.10.16 13:47	1278	15,6
07.10.16 6:42	1278	17,8
08.10.2016T 3:24:00	1279	14,8
03.10.16 1:03	1281	18,2
02.10.16 6:11	1283	12,6
02.10.16 19:24	1283	11,8
07.10.16 13:37	1288	16
08.10.2016T 19:46:00	1288	30,4
07.10.16 2:41	1291	13,4
01.10.16 17:29	1293	18,4
02.10.16 20:12	1293	20
02.10.16 23:36	1294	17
07.10.16 10:32	1296	26
03.10.16 20:41	1298	21
03.10.16 22:35	1298	19,4
05.10.16 12:19	1298	16
02.10.16 11:43	1300	12,8
03.10.16 23:18	1300	14
03.10.16 18:28	1302	21800000
02.10.16 8:06	1303	11,8
06.10.16 6:23	1303	25,8
03.10.16 10:42	1308	18
06.10.16 18:52	1308	10,2
06.10.16 16:16	1313	12
08.10.2016T 18:12:00	1313	13,8
02.10.16 14:04	1315	16,6
03.10.16 14:10	1318
03.10.16 18:15	1318
03.10.16 18:27	1318
04.10.16 17:09	1318
05.10.16 11:07	1318
06.10.16 1:46	1318
06.10.16 22:29	1318
07.10.16 0:44	1318
07.10.16 10:17	1318
07.10.16 11:29	1318
08.10.2016T 23:18:00	1318
09.10.2016T 1:37:00	1318
09.10.2016T 7:48:00	1318
09.10.2016T 22:27:00	1318
06.10.16 17:08	1320	18
09.10.2016T 2:35:00	1323	16
09.10.2016T 10:08:00	1323	28,6
05.10.16 7:29	1328	18,4
05.10.16 11:58	1328	18,8
03.10.16 0:36	1330	17,8
09.10.2016T 2:08:00	1331	16,8
03.10.16 2:19	1332	19,4
04.10.16 22:01	1333	20
08.10.2016T 3:48:00	1334	16
03.10.16 1:32	1343	22
08.10.2016T 4:34:00	1350	12800000
04.10.16 4:09	1351	20
06.10.16 19:09	1353	17,4
03.10.16 1:30	1354	15,6
02.10.16 23:30	1355	22
08.10.2016T 6:50:00	1359	14,4
02.10.16 13:33	1362	12,2
05.10.16 21:36	1363	12,2
04.10.16 22:06	1364	20
01.10.16 5:29	1366	13000000
07.10.16 9:40	1367	22,4
04.10.16 7:31	1371	13,6
04.10.16 1:36	1372	30,4
07.10.16 17:25	1374	12,4
05.10.16 23:06	1377	16
06.10.16 14:29	1380	30,4
09.10.2016T 4:55:00	1382	23,2
05.10.16 21:24	1383	20
05.10.16 8:14	1386	12,6
03.10.16 11:43	1387	14,6
01.10.16 6:21	1388	11,8
03.10.16 6:03	1392	20,2
06.10.16 5:34	1393	10
04.10.16 23:55	1394	12,8
05.10.16 5:01	1397	20,6
05.10.16 22:54	1398	18
01.10.16 17:01	1424
03.10.16 6:50	1424
04.10.16 5:27	1424
04.10.16 16:14	1424
04.10.16 18:21	1424
05.10.16 23:33	1424
06.10.16 7:27	1424
07.10.16 3:01	1424
07.10.16 16:08	1424
07.10.16 16:12	1424
08.10.2016T 12:41:00	1424
08.10.2016T 15:26:00	1424
08.10.2016T 17:21:00	1424
09.10.2016T 8:00:00	1424
10.10.16 1:24	1424

Чем прекрасен этот файл:
1. Даты имеют разный формат: за 8 и 9 октября формат с "09.10.2016 21:40" сменился на "09.10.2016T 21:40:00" (добавилась буква T и секунды). Разработчики объяснили этот тем, что сбились настройки после обновления одной из баз данных.
2. У покупок некоторых пользователей неизвестно значение выручки, из-за чего количество столбцов в строке уменьшается на один.
3. У некоторых строк реальная сумма покупки умножена на миллион. Так иногда действительно делают, чтобы избежать дробных чисел и работать только с целыми.

### Упражнение
Посчитайте сумму выручки из третьего столбца. Пока не обращайте внимания на помноженную на миллион выручку.

In [26]:
float('14,2'.replace(',', '.'))

14.2

In [32]:
def revenue(filename):
    """Возвращает сумму выручки в третьем столбце файла filename"""
    
    total_sum = 0
    with open(filename) as f:
        for line in f:
            line = line.strip().split('\t')
            
            try:
                value = float(line[2].replace(',', '.'))
            except:
                print('Битая строка', line)

            total_sum += value
    
    return total_sum
        
            
revenue('real_data.txt')

Битая строка ['05.10.16 3:23', '1041']
Битая строка ['05.10.16 23:19', '1041']
Битая строка ['01.10.16 13:39', '1047']
Битая строка ['05.10.16 21:41', '1047']
Битая строка ['04.10.16 11:12', '1057']
Битая строка ['09.10.2016T 2:47:00', '1057']
Битая строка ['01.10.16 14:16', '1100']
Битая строка ['02.10.16 1:39', '1100']
Битая строка ['02.10.16 2:49', '1100']
Битая строка ['02.10.16 13:05', '1100']
Битая строка ['03.10.16 4:04', '1100']
Битая строка ['03.10.16 6:58', '1100']
Битая строка ['03.10.16 15:01', '1100']
Битая строка ['04.10.16 23:43', '1100']
Битая строка ['05.10.16 5:46', '1100']
Битая строка ['06.10.16 0:31', '1100']
Битая строка ['06.10.16 9:25', '1100']
Битая строка ['08.10.2016T 15:15:00', '1100']
Битая строка ['04.10.16 5:00', '1134']
Битая строка ['06.10.16 12:01', '1134']
Битая строка ['01.10.16 15:58', '1135']
Битая строка ['02.10.16 3:19', '1135']
Битая строка ['02.10.16 19:24', '1135']
Битая строка ['04.10.16 10:40', '1135']
Битая строка ['06.10.16 6:06', '1135']
Битая строка ['06.10.16 16:08', '1135']
Битая строка ['08.10.2016T 0:31:00', '1135']
Битая строка ['08.10.2016T 10:16:00', '1135']
Битая строка ['08.10.2016T 23:10:00', '1135']
Битая строка ['05.10.16 13:55', '1203']
Битая строка ['06.10.16 5:56', '1203']
Битая строка ['01.10.16 4:41', '1226']
Битая строка ['03.10.16 9:32', '1226']
Битая строка ['01.10.16 9:02', '1233']
Битая строка ['01.10.16 10:27', '1233']
Битая строка ['02.10.16 4:27', '1246']
Битая строка ['02.10.16 8:45', '1246']
Битая строка ['02.10.16 16:58', '1246']
Битая строка ['02.10.16 17:30', '1246']
Битая строка ['02.10.16 19:46', '1246']
Битая строка ['03.10.16 2:05', '1246']
Битая строка ['03.10.16 2:57', '1246']
Битая строка ['03.10.16 7:19', '1246']
Битая строка ['03.10.16 12:15', '1246']
Битая строка ['03.10.16 14:58', '1246']
Битая строка ['03.10.16 19:43', '1246']
Битая строка ['04.10.16 7:27', '1246']
Битая строка ['04.10.16 9:08', '1246']
Битая строка ['04.10.16 13:52', '1246']
Битая строка ['04.10.16 16:34', '1246']
Битая строка ['05.10.16 0:27', '1246']
Битая строка ['05.10.16 6:36', '1246']
Битая строка ['05.10.16 12:59', '1246']
Битая строка ['05.10.16 16:52', '1246']
Битая строка ['05.10.16 17:26', '1246']
Битая строка ['06.10.16 6:48', '1246']
Битая строка ['08.10.2016T 2:53:00', '1246']
Битая строка ['10.10.16 0:59', '1246']
Битая строка ['02.10.16 21:42', '1267']
Битая строка ['04.10.16 9:02', '1267']
Битая строка ['04.10.16 12:10', '1267']
Битая строка ['04.10.16 15:40', '1267']
Битая строка ['04.10.16 18:37', '1267']
Битая строка ['04.10.16 21:29', '1267']
Битая строка ['05.10.16 21:11', '1267']
Битая строка ['05.10.16 22:09', '1267']
Битая строка ['06.10.16 3:58', '1267']
Битая строка ['06.10.16 11:16', '1267']
Битая строка ['06.10.16 19:20', '1267']
Битая строка ['07.10.16 10:18', '1267']
Битая строка ['08.10.2016T 18:18:00', '1267']
Битая строка ['09.10.2016T 4:41:00', '1267']
Битая строка ['09.10.2016T 9:13:00', '1267']
Битая строка ['09.10.2016T 15:37:00', '1267']
Битая строка ['09.10.2016T 18:56:00', '1267']
Битая строка ['03.10.16 14:10', '1318']
Битая строка ['03.10.16 18:15', '1318']
Битая строка ['03.10.16 18:27', '1318']
Битая строка ['04.10.16 17:09', '1318']
Битая строка ['05.10.16 11:07', '1318']
Битая строка ['06.10.16 1:46', '1318']
Битая строка ['06.10.16 22:29', '1318']
Битая строка ['07.10.16 0:44', '1318']
Битая строка ['07.10.16 10:17', '1318']
Битая строка ['07.10.16 11:29', '1318']
Битая строка ['08.10.2016T 23:18:00', '1318']
Битая строка ['09.10.2016T 1:37:00', '1318']
Битая строка ['09.10.2016T 7:48:00', '1318']
Битая строка ['09.10.2016T 22:27:00', '1318']
Битая строка ['01.10.16 17:01', '1424']
Битая строка ['03.10.16 6:50', '1424']
Битая строка ['04.10.16 5:27', '1424']
Битая строка ['04.10.16 16:14', '1424']
Битая строка ['04.10.16 18:21', '1424']
Битая строка ['05.10.16 23:33', '1424']
Битая строка ['06.10.16 7:27', '1424']
Битая строка ['07.10.16 3:01', '1424']
Битая строка ['07.10.16 16:08', '1424']
Битая строка ['07.10.16 16:12', '1424']
Битая строка ['08.10.2016T 12:41:00', '1424']
Битая строка ['08.10.2016T 15:26:00', '1424']
Битая строка ['08.10.2016T 17:21:00', '1424']
Битая строка ['09.10.2016T 8:00:00', '1424']
Битая строка ['10.10.16 1:24', '1424']

198204868.20000032

# Даты

In [ ]:
# иногда импортируют так
import datetime

In [ ]:
datetime.datetime.strptime()

In [ ]:
# можно и так
import datetime as dt

In [33]:
# у нас будет вариант покороче (но это не одно и то же)
from datetime import datetime

In [36]:
date_string = '09.05.2018 09:00'

In [35]:
# сейчас date_string это просто строка
type(date_string)

str

In [39]:
datetime.strptime('09.05.2018 09:00', '%d.%m.%Y %H:%M')

datetime.datetime(2018, 5, 9, 9, 0)

In [40]:
# https://docs.python.org/3/library/datetime.html

date_datetime = datetime.strptime( date_string, '%d.%m.%Y %H:%M' )
date_datetime

datetime.datetime(2018, 5, 9, 9, 0)

In [41]:
# теперь можем работать с датами
type(date_datetime)

datetime.datetime

In [42]:
# получить номер года и часа
date_datetime.year, date_datetime.hour

(2018, 9)

In [43]:
# день недели
date_datetime.weekday()

2

In [44]:
# сегодня
datetime.now()

datetime.datetime(2020, 3, 2, 20, 22, 5, 752261)

### Упражнение
С помощью метода datetime.strptime переведите строку 'May 25 2017 5:00AM' в формат datetime.

In [ ]:
datetime.strptime( date_string, '' )

In [45]:
datetime.strptime('May 25 2017 5:00AM', '%B %d %Y %H:%M%p')

datetime.datetime(2017, 5, 25, 5, 0)

In [46]:
date_string = 'May 25 2017 5:00AM'

datetime.strptime(date_string, '%b %d %Y %I:%M%p')

datetime.datetime(2017, 5, 25, 5, 0)

In [52]:
datetime.strptime('May 25 2017 5:00AM','%b %d %Y %H:%MAM')

datetime.datetime(2017, 5, 25, 5, 0)

In [51]:
datetime.strptime('May 25 2017 5:00AM', '%b %d %Y %I:%m')

ValueError: time data 'May 25 2017 5:00AM' does not match format '%b %d %Y %I:%m'

### Прибавление интервала к датам

In [53]:
from datetime import timedelta

In [54]:
start_date = '2018-01-01'
end_date = '2018-01-07'

In [55]:
type(start_date)

str

In [ ]:
'logs_2018-01-01.csv'
'logs_2018-01-02.csv'
'logs_2018-01-03.csv'

In [ ]:
'logs_01.01.2020.csv'
'logs_01.02.2020.csv'
'logs_01.03.2020.csv'
...
'logs_02.01.2020.csv'
'logs_02.02.2020.csv'

In [56]:
start_date_datetime = datetime.strptime(start_date, '%Y-%m-%d')
start_date_datetime

datetime.datetime(2018, 1, 1, 0, 0)

In [57]:
start_date_datetime + timedelta(days=1)

datetime.datetime(2018, 1, 2, 0, 0)

In [58]:
start_date_datetime - timedelta(days=1)

datetime.datetime(2017, 12, 31, 0, 0)

In [59]:
start_date_datetime + timedelta(days=-7, minutes=-1)

datetime.datetime(2017, 12, 24, 23, 59)

### Упражнение
Дана дата в формате '2018-09-01T09:30:00'. Прибавьте к ней 12 часов 15минут и 3 секунды.

### Перевод обратно в строку

In [60]:
date = datetime(2018, 9, 1)
date

datetime.datetime(2018, 9, 1, 0, 0)

In [61]:
date.strftime('%Y-%m-%d')

'2018-09-01'

In [62]:
date.strftime('%B %d %Y %I:%M%p')

'September 01 2018 12:00AM'

In [64]:
datetime.now().strftime('%Y-%m-01')

'2020-03-01'

In [63]:
# как получить первый день месяца

date.strftime('%Y-%m-01')

'2018-09-01'

In [65]:
start_date = '2018-01-01'
end_date = '2018-01-07'

In [66]:
start_date, end_date

('2018-01-01', '2018-01-07')

In [67]:
start_date_dt = datetime.strptime(start_date, '%Y-%m-%d')
end_date_dt = datetime.strptime(end_date, '%Y-%m-%d')

print(start_date_dt, end_date_dt)

2018-01-01 00:00:00 2018-01-07 00:00:00

In [68]:
i = 0

while i < 10:
    # ...
    i += 1
    print(i)

1
2
3
4
5
6
7
8
9
10

In [69]:
current_dt = start_date_dt

while current_dt <= end_date_dt:
    print(current_dt.strftime('%Y-%m-%d'))
    
    current_dt += timedelta(days=1)

2018-01-01
2018-01-02
2018-01-03
2018-01-04
2018-01-05
2018-01-06
2018-01-07

In [70]:
'2018-01-01' < '2018-01-02'

True

In [71]:
current_dt = start_date_dt

while current_dt.strftime('%Y-%m-%d') <= end_date:
    print(current_dt.strftime('%Y-%m-%d'))
    
    current_dt += timedelta(days=1)

2018-01-01
2018-01-02
2018-01-03
2018-01-04
2018-01-05
2018-01-06
2018-01-07

In [72]:
# можно и с помощью list comprehension
[(start_date_dt + timedelta(days=x)).strftime('%Y-%m-%d') for x in range(10)]

['2018-01-01',
 '2018-01-02',
 '2018-01-03',
 '2018-01-04',
 '2018-01-05',
 '2018-01-06',
 '2018-01-07',
 '2018-01-08',
 '2018-01-09',
 '2018-01-10']

### Упражнение
Напишите алгоритм, который "пробегает" период 1 до 7 сентября по часам. Формат вывода '06.01.2018 23:00:00'.

### Нагрузка на систему по часам

In [73]:
stats = {}

with open('logs.csv', 'r') as f:
    for line in f:
        line = line.strip()
        print(line)
        
        break
        
        # вычисления нагрузки на систему...
        
# результат
stats

2018-04-30T21:37:41Z

{}

In [80]:
stats = {}

with open('logs.csv', 'r') as f:
    for line in f:
        line = line.strip()
        
        # line = datetime.strptime(line, '%Y-%m-%dT%H:%M:%SZ')
        line = line[11:13]
        
        stats.setdefault(line, 0)
        stats[line] += 1
        
        # вычисления нагрузки на систему...
        
# результат
stats

{'21': 59,
 '20': 67,
 '23': 36,
 '22': 37,
 '18': 72,
 '13': 56,
 '11': 52,
 '00': 22,
 '16': 56,
 '17': 56,
 '15': 68,
 '19': 63,
 '12': 64,
 '10': 77,
 '01': 10,
 '07': 22,
 '05': 10,
 '09': 33,
 '06': 19,
 '14': 57,
 '08': 42,
 '03': 7,
 '02': 8,
 '04': 7}

In [ ]:
# а в процентном соотношении?

###  Unixtime
Количество секунд, прошедших с 1 января 1970 года по UTC

In [81]:
import time
from datetime import date
from datetime import datetime

In [82]:
d = date(2019, 3, 11)

unixtime = time.mktime(d.timetuple())
unixtime

1552251600.0

In [83]:
from datetime import datetime

In [84]:
datetime.fromtimestamp(1552251600)

datetime.datetime(2019, 3, 11, 0, 0)

На практике все сложнее https://habr.com/ru/post/452584/

# Задача про интервалы
Имеется список отсортированных по возрастанию целых чисел data. А также целое число n, которое лежит между минимальным и максимальным значениями из списка data. Вам необходимо определить минимальное ближайшее число к n из списка data.

Пример:
```python
data = [1, 7, 17, 23, 27, 35, 65]
n = 20
```

Ответ: 17

Подобные алгоритмы используются для классификации объекта по значению одной метрики. Например, это может пригодиться для классификации учащегося по его возрасту:
```python
ages = {
    1: 'дети',
    7: 'школьники',
    17: 'студенты',
    23: 'аспиранты',
    27: 'молодые ученые',
    35: 'преподаватели',
    65: 'пенсионеры',
}
```

Итого напишите функцию, которая по списку data и числу n возвращает минимальное ближайшее к n число. Список может быть любым, поэтому не рассчитывайте на написание цепочки условий через if.

Бонусные варианты:
1. Рассмотрите ситуацию, в которой при фиксированном списке data вам необходимо классифицировать большое количество пользователей с разными значениями n. Например, вам необходимо классифицировать базу из 100 миллионов человек по возрастам по словарю ages из примера выше. Можно ли в таком случае ускорить проход по такому числу пользователей?

2. Если вы решали основное задание перебором элементов списка data и сравнением с n, то сложность такого алгоритма O(N). Т. е. при увеличении числа элементов списка data в N раз время работы алгоритма тоже вырастет в N раз. Попробуйте ускорить этот алгоритм. Например, с помощью аналога бинарного поиска.